language: cpp

matrix:
  include:
  - os: linux
    dist: bionic
    sudo: required
    install:
    - sudo add-apt-repository -y ppa:beineri/opt-qt-5.12.6-bionic # 5.12 here because there is no ppa for 5.13 for 18.04
    - sudo apt-get update
    - sudo apt-get install qt512-meta-full libgl-dev
    script:
    - mkdir build && cd build
    - cmake .. -DQTDIR="/opt/qt512"
    - cmake --build .
  - os: osx
    osx_image: xcode11.2
    script:
    - mkdir build && cd build
    - cmake .. -DQTDIR="/usr/local/Cellar/qt/5.13.2"
    - cmake --build .

