language: cpp

dist: bionic
sudo: required
osx_image: xcode11.2

os:
  - linux
  - osx

#before_install:
#   - '[ "$TRAVIS_OS_NAME" != osx ] || brew update'

install:
  # Install conan
  #- python3 --version
  #- alias python='python3'
#  - pip3 install --upgrade setuptools
#  - pip3 install --user -q conan
  # Automatic detection of your arch, compiler, etc.
  #- conan user
#  - conan profile new --detect default
#  - conan profile update settings.compiler.libcxx=libstdc++11 default
   - '[ "$TRAVIS_OS_NAME" != linux ] || sudo add-apt-repository -y ppa:beineri/opt-qt-5.12.6-bionic'
   - '[ "$TRAVIS_OS_NAME" != linux ] || sudo apt-get update'
   - '[ "$TRAVIS_OS_NAME" != linux ] || sudo apt-get install qt512-meta-full libgl-dev'
#   - '[ "$TRAVIS_OS_NAME" != osx ] || brew install qt'
#   - '[ "$TRAVIS_OS_NAME" != osx ] || brew link --force qt'


script:
  - mkdir build && cd build
#  - conan remote add bincrafters "https://api.bintray.com/conan/bincrafters/public-conan"
#  - conan install .. --build=missing -e PYTHONPATH=/usr/bin/python3
  - '[ "$TRAVIS_OS_NAME" != linux ] || cmake .. -DQTDIR="/opt/qt512"'
  - '[ "$TRAVIS_OS_NAME" != osx ] || cmake .. -DQTDIR="/usr/local/Cellar/qt/5.13.2"'
  - cmake --build .
#  - ./example

matrix:
#  include:
#    - os: linux
#      addons:
#        apt:
#          packages:
#            - python3-pip
