######################################################################
# Automatically generated by qmake (3.1) Sun Oct 27 12:10:06 2019
######################################################################

TEMPLATE = app
TARGET = AngryBirds
INCLUDEPATH += .

# You can make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# Please consult the documentation of the deprecated API in order to know
# how to port your code away from it.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

# Input
HEADERS += src/ldAngryBirds.h \
           src/vis/ldAngryBirdsVisualizer.h \
           src/vis/impl/Box2D.h \
           src/vis/impl/globals.h \
           src/vis/impl/ldAngryBirdsBox.h \
           src/vis/impl/ldAngryBirdsPlayer.h \
           src/vis/impl/spline.h \
           src/vis/impl/Box2D/Collision/b2BroadPhase.h \
           src/vis/impl/Box2D/Collision/b2Collision.h \
           src/vis/impl/Box2D/Collision/b2Distance.h \
           src/vis/impl/Box2D/Collision/b2DynamicTree.h \
           src/vis/impl/Box2D/Collision/b2TimeOfImpact.h \
           src/vis/impl/Box2D/Common/b2BlockAllocator.h \
           src/vis/impl/Box2D/Common/b2Draw.h \
           src/vis/impl/Box2D/Common/b2GrowableStack.h \
           src/vis/impl/Box2D/Common/b2Math.h \
           src/vis/impl/Box2D/Common/b2Settings.h \
           src/vis/impl/Box2D/Common/b2StackAllocator.h \
           src/vis/impl/Box2D/Common/b2Timer.h \
           src/vis/impl/Box2D/Dynamics/b2Body.h \
           src/vis/impl/Box2D/Dynamics/b2ContactManager.h \
           src/vis/impl/Box2D/Dynamics/b2Fixture.h \
           src/vis/impl/Box2D/Dynamics/b2Island.h \
           src/vis/impl/Box2D/Dynamics/b2TimeStep.h \
           src/vis/impl/Box2D/Dynamics/b2World.h \
           src/vis/impl/Box2D/Dynamics/b2WorldCallbacks.h \
           src/vis/impl/Box2D/Rope/b2Rope.h \
           src/vis/impl/Box2D/Collision/Shapes/b2ChainShape.h \
           src/vis/impl/Box2D/Collision/Shapes/b2CircleShape.h \
           src/vis/impl/Box2D/Collision/Shapes/b2EdgeShape.h \
           src/vis/impl/Box2D/Collision/Shapes/b2PolygonShape.h \
           src/vis/impl/Box2D/Collision/Shapes/b2Shape.h \
           src/vis/impl/Box2D/Dynamics/Contacts/b2ChainAndCircleContact.h \
           src/vis/impl/Box2D/Dynamics/Contacts/b2ChainAndPolygonContact.h \
           src/vis/impl/Box2D/Dynamics/Contacts/b2CircleContact.h \
           src/vis/impl/Box2D/Dynamics/Contacts/b2Contact.h \
           src/vis/impl/Box2D/Dynamics/Contacts/b2ContactSolver.h \
           src/vis/impl/Box2D/Dynamics/Contacts/b2EdgeAndCircleContact.h \
           src/vis/impl/Box2D/Dynamics/Contacts/b2EdgeAndPolygonContact.h \
           src/vis/impl/Box2D/Dynamics/Contacts/b2PolygonAndCircleContact.h \
           src/vis/impl/Box2D/Dynamics/Contacts/b2PolygonContact.h \
           src/vis/impl/Box2D/Dynamics/Joints/b2DistanceJoint.h \
           src/vis/impl/Box2D/Dynamics/Joints/b2FrictionJoint.h \
           src/vis/impl/Box2D/Dynamics/Joints/b2GearJoint.h \
           src/vis/impl/Box2D/Dynamics/Joints/b2Joint.h \
           src/vis/impl/Box2D/Dynamics/Joints/b2MotorJoint.h \
           src/vis/impl/Box2D/Dynamics/Joints/b2MouseJoint.h \
           src/vis/impl/Box2D/Dynamics/Joints/b2PrismaticJoint.h \
           src/vis/impl/Box2D/Dynamics/Joints/b2PulleyJoint.h \
           src/vis/impl/Box2D/Dynamics/Joints/b2RevoluteJoint.h \
           src/vis/impl/Box2D/Dynamics/Joints/b2RopeJoint.h \
           src/vis/impl/Box2D/Dynamics/Joints/b2WeldJoint.h \
           src/vis/impl/Box2D/Dynamics/Joints/b2WheelJoint.h \
           /src/vis/impl/Box2D/Common/b2Math.h \
           /src/vis/impl/Box2D/Common/b2Settings.h \
           /src/vis/impl/Box2D/Collision/Shapes/b2Shape.h \
           /src/vis/impl/Box2D/Common/b2BlockAllocator.h \
           /src/vis/impl/Box2D/Collision/b2Collision.h \
           /src/vis/impl/Box2D/Collision/b2DynamicTree.h \
           /src/vis/impl/Box2D/Common/b2GrowableStack.h \
           /src/vis/impl/Box2D/Collision/b2Distance.h \
           /src/vis/impl/Box2D/Dynamics/b2Body.h \
           /src/vis/impl/Box2D/Common/b2StackAllocator.h \
           /src/vis/impl/Box2D/Dynamics/b2ContactManager.h \
           /src/vis/impl/Box2D/Collision/b2BroadPhase.h \
           /src/vis/impl/Box2D/Dynamics/b2WorldCallbacks.h \
           /src/vis/impl/Box2D/Dynamics/b2TimeStep.h \
           /src/vis/impl/Box2D/Dynamics/b2Fixture.h \
           /src/vis/impl/Box2D/Dynamics/Joints/b2Joint.h \
           /src/vis/impl/Box2D/Collision/Shapes/b2CircleShape.h \
           /src/vis/impl/Box2D/Collision/Shapes/b2PolygonShape.h \
           /src/vis/impl/Box2D/Collision/Shapes/b2EdgeShape.h \
           /src/vis/impl/Box2D/Collision/Shapes/b2ChainShape.h \
           /src/vis/impl/Box2D/Collision/b2TimeOfImpact.h \
           /src/vis/impl/Box2D/Common/b2Timer.h \
           /src/vis/impl/Box2D/Common/b2Draw.h \
           /src/vis/impl/Box2D/Dynamics/b2World.h \
           /src/vis/impl/Box2D/Dynamics/Contacts/b2Contact.h \
           /src/vis/impl/Box2D/Dynamics/b2Island.h \
           /src/vis/impl/Box2D/Dynamics/Contacts/b2ContactSolver.h \
           /src/vis/impl/Box2D/Dynamics/Joints/b2PulleyJoint.h \
           /src/vis/impl/Box2D/Rope/b2Rope.h \
           /src/vis/impl/Box2D/Dynamics/Contacts/b2ChainAndCircleContact.h \
           /src/vis/impl/Box2D/Dynamics/Contacts/b2ChainAndPolygonContact.h \
           /src/vis/impl/Box2D/Dynamics/Contacts/b2CircleContact.h \
           /src/vis/impl/Box2D/Dynamics/Contacts/b2PolygonAndCircleContact.h \
           /src/vis/impl/Box2D/Dynamics/Contacts/b2PolygonContact.h \
           /src/vis/impl/Box2D/Dynamics/Contacts/b2EdgeAndCircleContact.h \
           /src/vis/impl/Box2D/Dynamics/Contacts/b2EdgeAndPolygonContact.h \
           /src/vis/impl/Box2D/Dynamics/Joints/b2DistanceJoint.h \
           /src/vis/impl/Box2D/Dynamics/Joints/b2FrictionJoint.h \
           /src/vis/impl/Box2D/Dynamics/Joints/b2GearJoint.h \
           /src/vis/impl/Box2D/Dynamics/Joints/b2RevoluteJoint.h \
           /src/vis/impl/Box2D/Dynamics/Joints/b2PrismaticJoint.h \
           /src/vis/impl/Box2D/Dynamics/Joints/b2WheelJoint.h \
           /src/vis/impl/Box2D/Dynamics/Joints/b2MouseJoint.h \
           /src/vis/impl/Box2D/Dynamics/Joints/b2WeldJoint.h \
           /src/vis/impl/Box2D/Dynamics/Joints/b2RopeJoint.h \
           /src/vis/impl/Box2D/Dynamics/Joints/b2MotorJoint.h
SOURCES += src/ldAngryBirds.cpp \
           src/vis/ldAngryBirdsVisualizer.cpp \
           src/vis/impl/ldAngryBirdsBox.cpp \
           src/vis/impl/ldAngryBirdsPlayer.cpp \
           src/vis/impl/spline.cpp \
           src/vis/impl/Box2D/Collision/b2BroadPhase.cpp \
           src/vis/impl/Box2D/Collision/b2CollideCircle.cpp \
           src/vis/impl/Box2D/Collision/b2CollideEdge.cpp \
           src/vis/impl/Box2D/Collision/b2CollidePolygon.cpp \
           src/vis/impl/Box2D/Collision/b2Collision.cpp \
           src/vis/impl/Box2D/Collision/b2Distance.cpp \
           src/vis/impl/Box2D/Collision/b2DynamicTree.cpp \
           src/vis/impl/Box2D/Collision/b2TimeOfImpact.cpp \
           src/vis/impl/Box2D/Common/b2BlockAllocator.cpp \
           src/vis/impl/Box2D/Common/b2Draw.cpp \
           src/vis/impl/Box2D/Common/b2Math.cpp \
           src/vis/impl/Box2D/Common/b2Settings.cpp \
           src/vis/impl/Box2D/Common/b2StackAllocator.cpp \
           src/vis/impl/Box2D/Common/b2Timer.cpp \
           src/vis/impl/Box2D/Dynamics/b2Body.cpp \
           src/vis/impl/Box2D/Dynamics/b2ContactManager.cpp \
           src/vis/impl/Box2D/Dynamics/b2Fixture.cpp \
           src/vis/impl/Box2D/Dynamics/b2Island.cpp \
           src/vis/impl/Box2D/Dynamics/b2World.cpp \
           src/vis/impl/Box2D/Dynamics/b2WorldCallbacks.cpp \
           src/vis/impl/Box2D/Rope/b2Rope.cpp \
           src/vis/impl/Box2D/Collision/Shapes/b2ChainShape.cpp \
           src/vis/impl/Box2D/Collision/Shapes/b2CircleShape.cpp \
           src/vis/impl/Box2D/Collision/Shapes/b2EdgeShape.cpp \
           src/vis/impl/Box2D/Collision/Shapes/b2PolygonShape.cpp \
           src/vis/impl/Box2D/Dynamics/Contacts/b2ChainAndCircleContact.cpp \
           src/vis/impl/Box2D/Dynamics/Contacts/b2ChainAndPolygonContact.cpp \
           src/vis/impl/Box2D/Dynamics/Contacts/b2CircleContact.cpp \
           src/vis/impl/Box2D/Dynamics/Contacts/b2Contact.cpp \
           src/vis/impl/Box2D/Dynamics/Contacts/b2ContactSolver.cpp \
           src/vis/impl/Box2D/Dynamics/Contacts/b2EdgeAndCircleContact.cpp \
           src/vis/impl/Box2D/Dynamics/Contacts/b2EdgeAndPolygonContact.cpp \
           src/vis/impl/Box2D/Dynamics/Contacts/b2PolygonAndCircleContact.cpp \
           src/vis/impl/Box2D/Dynamics/Contacts/b2PolygonContact.cpp \
           src/vis/impl/Box2D/Dynamics/Joints/b2DistanceJoint.cpp \
           src/vis/impl/Box2D/Dynamics/Joints/b2FrictionJoint.cpp \
           src/vis/impl/Box2D/Dynamics/Joints/b2GearJoint.cpp \
           src/vis/impl/Box2D/Dynamics/Joints/b2Joint.cpp \
           src/vis/impl/Box2D/Dynamics/Joints/b2MotorJoint.cpp \
           src/vis/impl/Box2D/Dynamics/Joints/b2MouseJoint.cpp \
           src/vis/impl/Box2D/Dynamics/Joints/b2PrismaticJoint.cpp \
           src/vis/impl/Box2D/Dynamics/Joints/b2PulleyJoint.cpp \
           src/vis/impl/Box2D/Dynamics/Joints/b2RevoluteJoint.cpp \
           src/vis/impl/Box2D/Dynamics/Joints/b2RopeJoint.cpp \
           src/vis/impl/Box2D/Dynamics/Joints/b2WeldJoint.cpp \
           src/vis/impl/Box2D/Dynamics/Joints/b2WheelJoint.cpp
