macro(ld_add_executable TARGET)
    if(QT_VERSION_MAJOR EQUAL 6)
        qt_add_executable(${TARGET} MACOSX_BUNDLE WIN32)
    else()
        if (ANDROID)
            add_library(${TARGET} SHARED)
        else()
            add_executable(${TARGET} MACOSX_BUNDLE WIN32)
        endif()
    endif()
endmacro()
