macro(setup_cpp_flags TARGET)
if(UNIX)
    target_compile_options(${TARGET} PUBLIC -Wall -Wextra -Wuninitialized -Winit-self -Wno-unknown-pragmas -Wpedantic)
    if("${CMAKE_CXX_COMPILER_ID}" STREQUAL "GNU")
        target_compile_options(${TARGET} PUBLIC -fPIC)
    endif()
    if(NOT ANDROID)
        target_compile_options(${TARGET} PUBLIC -Wshadow)
    endif()
endif()
endmacro()
